travis:
  secure:
    BINSTAR_TOKEN: jOH93Nwi/ZaC1iviI4PriFmo5HkR7vDEum0fMR7N6Rv9EcbGnIA5FngIIRonXo4U36cvKA3gK+ZcmXcKRajIKD3m8QQ/kfITG22UOUVKTAryTfEF6GXDt1CJG5Eb0x/POp2K1ao8gSrCFB7VW8a4EaEax3RZKTLQoKtvAG4+SADDeKkz+QAROEQG226f1jvw48vjKI3vSNtoUaz7PCdvqMPygO8ObvDmqIx793XUfodY015Am1rO61p2IqWyQ81mDy+2tqUAESL0NfwlQF8w2lbRc6IZINrfs6/SggtKr/p9/E0EP/pNnCEYkJOlMmkuPrq+GA8brhlxsmObVXjYcqD0id/5+e2sXH+MHnYdYw7yfKSm0qlfu/d2+SVxHJqInYcEht5JWea5wV4+EDrHzUHXrjn9aDoF9hlujPB+Vpz8M0AHRqMXLGvOFfB5INlySsCIbjSUNOGh6KssnmdQ8gUp2Dmzc8EPB39KnX/RmSdw37Xil+RF3vDjFc3bhBLyTSM4umJkdsSn7iZmLfm3zgy5+3LGkPnUVKJ9HxY4ELGMEhXFHxb+kUQlUF+ft3/wBr5u0e4PK9giCn6uyA5RvGupm7fzwmwlAcrlGuaumr6skP4ty8oVgDMJ1gCOy/Qi8pJEq73kb6EvMM26t+pZoy+39FpHspOJ0OTQGSzwirU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
